package pl.sdacademy.enums;

public enum State {
    INIT,
    LOGGING_IN_AS_ADMIN,
    LOGGING_IN_AS_ACCOUNTANT,
    LOGGED_IN_AS_ACCOUNTANT,
    LOGGED_IN_AS_ADMIN,
    CREATING_COMPANY,
    CHANGE_COMPANY,
    CREATING_ADMIN,
    DELETING_ADMIN,
    CREATING_ACCOUNTANT,
    DELETING_ACCOUNTANT,
    CREATING_INVOICE,
    DELETING_COMPANY,
    CREATING_ACCOUNTANT_COMPANY_ASSOCIATION,
    EXIT,
}
